--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Laith98Dev/TempBan
build-by-default: true
branches:
- master
projects:
  TempBan:
    path: ""
    icon: "./images/20220331_180103.png"
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.0.1
      - src: Vecnavium/FormsUI/libFormsUI
        version: ^2.0.0
...
