name: TempBan
main: SonsaYT\TempBanUI\Main
api: [4.0.0]
version: 2.4.0
authors: [SonsaYT, Laith98Dev]

commands:
 tcheck:
  description: "Check ban list"
  permission: tempban.command.tcheck

permissions:
  tempban.command:
    default: op
  tempban.command.tcheck:
    default: op
